-- Structured 2-line product title for the card UI: "Brand + Model\nattributes".
-- Generated by the LLM (from the deal copy) so titles are consistent and short,
-- instead of verbose marketplace copy. Nullable + additive — the app falls back
-- to a heuristically-cleaned title when this is empty, so prod is unaffected.
ALTER TABLE deals ADD COLUMN IF NOT EXISTS display_title text;
