const { withAndroidManifest } = require("@expo/config-plugins");

/**
 * Resolves a manifest-merger conflict between expo-notifications and
 * @react-native-firebase/messaging.
 *
 * Both libraries declare the same Firebase meta-data keys:
 *   • expo-notifications  → default_notification_color = @color/notification_icon_color
 *                           default_notification_icon  = @drawable/notification_icon
 *   • rnfirebase/messaging→ default_notification_color = @color/white
 *
 * Android's merger refuses to choose and fails the build with:
 *   "Attribute meta-data#...default_notification_color@resource ... is also
 *    present at [:react-native-firebase_messaging] ... Suggestion: add
 *    tools:replace="android:resource""
 *
 * We want OUR values to win (the amber ⚡ branding), so we do exactly what the
 * merger suggests and mark these attributes as deliberate overrides. Applied to
 * the icon key too — it doesn't conflict today, but would the moment RNFirebase
 * starts declaring one, and the fix is identical.
 */
const OVERRIDE_KEYS = [
  "com.google.firebase.messaging.default_notification_color",
  "com.google.firebase.messaging.default_notification_icon",
];

module.exports = function withNotificationManifestFix(config) {
  return withAndroidManifest(config, (cfg) => {
    const manifest = cfg.modResults.manifest;
    const application = manifest.application && manifest.application[0];
    if (!application) return cfg;

    // The template already declares xmlns:tools, but a manifest generated by a
    // different template may not — tools:replace is inert without it.
    manifest.$ = manifest.$ || {};
    if (!manifest.$["xmlns:tools"]) {
      manifest.$["xmlns:tools"] = "http://schemas.android.com/tools";
    }

    for (const meta of application["meta-data"] || []) {
      if (meta.$ && OVERRIDE_KEYS.includes(meta.$["android:name"])) {
        meta.$["tools:replace"] = "android:resource";
      }
    }
    return cfg;
  });
};
